data:
  path: '../../Daten'
  freq: '1h'
  train_frac: 0.75
  lag_dim: 48
  horizon: 48
  scale_y: False
  lag_in_col: False

hpo:
  studies_dir: 'studies'
  trials: 1000
  kfolds: 5
  val_split: 0.75
  batch_size: [16, 256]
  epochs: [2, 100]
  n_layers: [1, 4]
  n_cnn_layers: [1, 4]
  n_rnn_layers: [1, 4]
  learning_rate: [0.0001, 0.1]
  fnn:
    units: [32, 256]
  cnn:
    filters: [16, 64]
    kernel_size: [2, 5]
  rnn:
    units: [16, 128]

model:
  output_dim: 1
  optimizer: 'adam'
  loss: 'mse'
  metrics: ['mae', 'rmse']
  callbacks: False
  save_model: True
  shuffle: False
  verbose: 1

eval:
  results_path: 'results'
  eval_on_all_test_data: False
  t_0: 12