data:
  path: 'data'
  freq: '1h'
  train_frac: 0.75
  val_frac: 0.25 # abs from train_frac
  test_start: '2019-03-01'
  scale_y: False
  lag_in_col: False
  n_neighbors: 5

model:
  output_dim: 48
  lookback: 48
  horizon: 48
  batch_size: 512
  epochs: 10
  lr: 0.001
  optimizer: 'adam'
  loss: 'mse'
  metrics: ['mae', 'rmse']
  fnn:
    units: 128
    n_layers: 2
  cnn:
    filters: 64
    kernel_size: 3
    n_cnn_layers: 3
    increase_filters: False
  rnn:
    n_rnn_layers: 1
    units: 64
    dropout: 0.1
  tft:
    n_heads: 1
    hidden_dim: 45
    dropout: 0.1
  callbacks: False
  save_model: True
  shuffle: False
  force_retrain: True
  parallelize: False
  verbose: 1

hpo:
  studies_path: '/mnt/nas/optuna_studies.db'
  metric: 'rmse'
  trials: 1000
  kfolds: 5
  val_split: 0.75
  batch_size: [64, 512]
  epochs: [1, 20]
  n_layers: [1, 4]
  n_cnn_layers: [1, 4]
  n_rnn_layers: [1, 2]
  learning_rate: [0.0001, 0.1]
  fnn:
    units: [32, 256]
  cnn:
    filters: [16, 64]
    kernel_size: [2, 5]
    increase_filters: False
  rnn:
    units: [16, 100]
  tft:
    lookback: [24, 48, 72, 96]
    n_heads: [1, 6]
    hidden_dim: [8, 128]
    dropout: [0.0, 0.5]
  fl:
    strategy: 'fedavg'
    personalize: False
    n_rounds: [1,20]
    server_lr: [0.0001, 0.1]
    beta_1: [0,1]
    beta_2: [0,1]
    tau: [0.0001, 0.1]

eval:
  results_path: 'results'
  eval_on_all_test_data: True
  retrain_interval: 0 # in hours - 0 if no retraining is wanted
  t_0: 12

fl:
  parts: []
  strategy: 'fedavg'
  n_rounds: 3
  personalize: False
  fedopt:
    server_lr: 0.001
    beta_1: 0.9
    beta_2: 0.99
    tau: 0.001
  force_retrain: True
  verbose: True
  save_history: False
  num_gpus: 1
  num_cpus: 11