data:
  path: '../../Data'
  freq: '1h'
  train_frac: 0.5
  val_frac: 0.25 # from train_frac
  scale_y: False
  lag_in_col: False

model:
  output_dim: 1
  lookback: 48
  horizon: 48
  batch_size: 16
  epochs: 20
  lr: 0.0004
  optimizer: 'adam'
  loss: 'mse'
  metrics: ['mae', 'rmse']
  fnn:
    units: 128
    n_layers: 2
  cnn:
    filters: 64
    kernel_size: 2
    n_cnn_layers: 2
  rnn:
    n_rnn_layers: 2
    units: 64
    dropout: 0.1
  tft:
    n_heads: 2
    hidden_dim: 60
    dropout: 0.1
  callbacks: False
  save_model: True
  shuffle: False
  verbose: 1

hpo:
  studies_dir: 'studies'
  metric: 'rmse'
  trials: 1000
  kfolds: 5
  val_split: 0.75
  batch_size: [16, 256]
  epochs: [1, 2]
  n_layers: [1, 4]
  n_cnn_layers: [1, 4]
  n_rnn_layers: [1, 4]
  learning_rate: [0.0001, 0.1]
  fnn:
    units: [32, 256]
  cnn:
    filters: [16, 64]
    kernel_size: [2, 5]
  rnn:
    units: [16, 128]
  tft:
    lookback: [24, 48, 72, 96]
    n_heads: [1, 6]
    hidden_dim: [8, 128]
    dropout: [0.0, 0.5]

eval:
  results_path: 'results'
  eval_on_all_test_data: True
  retrain_interval: 24 # in hours - 0 if no retraining is wanted
  t_0: 12

fl:
  parts: []
  n_rounds: 2
  n_clients: 9
  verbose: True
  save_history: True