data:
  path: '../../Data'
  freq: '1h'
  train_frac: 0.75
  val_frac: 0.75 # from train_frac
  scale_y: False
  lag_in_col: False

hpo:
  studies_dir: 'studies'
  metric: 'rmse'
  trials: 1000
  kfolds: 5
  val_split: 0.75
  batch_size: [16, 256]
  epochs: [1, 2]
  n_layers: [1, 4]
  n_cnn_layers: [1, 4]
  n_rnn_layers: [1, 4]
  learning_rate: [0.0001, 0.1]
  fnn:
    units: [32, 256]
  cnn:
    filters: [16, 64]
    kernel_size: [2, 5]
  rnn:
    units: [16, 128]
  tft:
    lookback: [24, 48, 72, 96]
    n_heads: [1, 6]
    hidden_dim: [8, 128]
    dropout: [0.0, 0.5]

model:
  output_dim: 1
  lookback: 48
  horizon: 48
  optimizer: 'adam'
  loss: 'mse'
  metrics: ['mae', 'rmse']
  callbacks: False
  save_model: True
  shuffle: False
  verbose: 1

eval:
  results_path: 'results'
  eval_on_all_test_data: False
  t_0: 12