data:
  ecmwf_path: /mnt/lambda1/nvme1/ecmwf/parquet
  files:
  - 00183
  - '00460'
  - 00856
  - '05404'
  - '01443'
  - 01684
  - 01759
  - '03032'
  - 03158
  - '03631'
  - '03730'
  - 05792
  - 05856
  - '15000'
  - 05779
  - '04271'
  - 02638
  - 02961
  - 05490
  - '05426'
  - '03761'
  - '00303'
  - 02483
  - 00596
  - '03513'
  - 00691
  - '01200'
  - '02014'
  - '02667'
  - '04036'
  - 04911
  - '00662'
  - '00232'
  - 05109
  - '01605'
  - 05871
  - '15813'
  - '05142'
  - 01691
  - '01544'
  - '07370'
  - 04931
  - 05797
  - '05705'
  - '01001'
  - '00161'
  - '07341'
  - '00433'
  - 00298
  - 02932
  - '02023'
  - 01048
  - 02794
  - '13674'
  - 03668
  - 05538
  - 01975
  - '04625'
  - '01270'
  - '02171'
  - '04104'
  - '05100'
  - '01503'
  - 03093
  - 03098
  - 03287
  - 03086
  - 04393
  - '03402'
  - 04094
  - '00704'
  - 05349
  - '01766'
  - 02985
  - '06163'
  - '01357'
  - 01468
  - 00880
  - '04371'
  - 01886
  - '01420'
  - '03015'
  - '04464'
  - 03196
  - '04466'
  - 00853
  - '02044'
  - '06344'
  - 00963
  - '03321'
  - 02559
  - '07351'
  - 04280
  - 02597
  - '00164'
  - 07389
  - '03231'
  - 01639
  - 06197
  - '06314'
  - 02485
  - 02856
  - 07396
  freq: 1h
  interpol_path: /mnt/lambda1/nvme1/synthetic/interpol/wind
  knnimputer_path: /mnt/lambda1/nvme1/synthetic/knnimputer/wind
  nwp_path: /mnt/lambda1/nvme1/icon-d2/parquet
  path: /mnt/lambda1/nvme1/synthetic/raw/wind
  stations_master: data/stations_master.csv
  test_end: '2025-10-31'
  test_files:
  - 00096
  - '00427'
  - '00603'
  - '05371'
  - 00840
  - 00867
  - 00891
  - 00953
  - '01262'
  - '01303'
  - 05906
  - '01612'
  - 01803
  - 01832
  - 02290
  - 02429
  - '02564'
  - '02601'
  - '07410'
  - 02878
  - 02925
  - 02928
  - '03166'
  - 03268
  - '03362'
  - '03660'
  - 03897
  - 03946
  - 03987
  - '04024'
  - '04032'
  - 00198
  - 04039
  - '04177'
  - '04336'
  - '13711'
  - '04501'
  - 04928
  - 05158
  - '05347'
  - '01346'
  - '05440'
  - '05546'
  - 07394
  - 07395
  - '07403'
  - '15444'
  - '19207'
  - '00722'
  - '00342'
  test_start: '2025-08-01'
  use_case: wind
  val_files:
  - '01550'
  - 02907
  - 07393
  - 02497
  - '01757'
  - '07367'
  - 02812
  - 05397
  - '07412'
  - 06159
  - 00591
  - 05825
  - 03821
  - 04887
  - '03366'
  - '05516'
  - '02712'
  - 05029
  - 07368
  - 05480
  - '00701'
  - '03167'
  - 01358
  - '03126'
  - 05800
  - 01587
  - 01694
  - 00282
  - 01869
  - 03925
  - '03376'
  - '19171'
  - '07374'
  - '00656'
  - '02115'
  - 01078
  - 03811
  - '03244'
  - '04642'
  - '15207'
  - '04745'
  - 01580
  - '02261'
  - 05629
  - 03379
  - '02252'
  - 05930
  - '13965'
  - 03028
  - 07369
  val_frac: 0.25
wavenet:
  K_hop: 2
  aggregate_nwp: false
  dropout: 0.2
  ecmwf_feature_mode: dir_in_deg
  ecmwf_features:
  - u_wind10m
  - v_wind10m
  - wind_speed_10m
  emb_dim: 64
  forecast_horizon: 48
  grad_accum: 4
  gradient_clip: 5.0
  graph_alpha: 3.0
  handle_nans: break
  hidden: 64
  hist_wind_available: true
  history_length: 48
  horizon_decay: 0.9
  hpo:
    max_epochs_per_trial: 100
    min_train_date: '2024-03-31'
    n_folds: 3
    n_val_stations: 50
    params:
      K_hop:
        high: 3
        low: 1
        type: int
      dropout:
        high: 0.4
        low: 0.0
        type: float
      ecmwf_feature_mode:
        choices:
        - absolute
        - dir_in_deg
        type: categorical
      emb_dim:
        high: 128
        low: 16
        step: 4
        type: int
      grad_accum:
        high: 64
        low: 1
        type: int
      gradient_clip:
        high: 10.0
        low: 0.5
        type: float
      graph_alpha:
        high: 6.0
        low: 1.0
        type: float
      hidden:
        high: 128
        low: 32
        type: int
      horizon_decay:
        high: 0.99
        low: 0.5
        type: float
      icond2_feature_mode:
        choices:
        - absolute
        - dir_in_deg
        type: categorical
      kernel_size:
        high: 4
        low: 2
        type: int
      lr:
        high: 0.001
        log: true
        low: 1.0e-05
        type: float
      n_blocks:
        high: 18
        low: 8
        type: int
      next_n_ecmwf:
        high: 4
        low: 0
        type: int
      next_n_icond2:
        high: 7
        low: 1
        type: int
      next_n_neighbors:
        high: 90
        low: 50
        type: int
      weight_decay:
        high: 0.001
        log: true
        low: 1.0e-06
        type: float
    patience_per_trial: 10
    pruner: median
    pruner_n_startup_trials: 20
    pruner_n_warmup_steps: 1
    studies_path: studies/
    tensorboard_monitoring: true
    trials: 1000
  icond2_feature_mode: dir_in_deg
  icond2_features:
  - u_10m
  - v_10m
  - wind_speed_10m
  - wind_speed_38m
  icond2_run_hours:
  - 6
  - 9
  - 12
  - 15
  kernel_size: 2
  loss_weights_by_horizon: true
  lr: 0.0003
  max_epochs: 200
  max_neighbor_stations: 90
  max_target_stations: 10
  measurement_features:
  - wind_speed
  - wind_direction
  min_target_stations: 1
  n_blocks: 12
  n_workers: 8
  next_n_ecmwf: 4
  next_n_icond2: 4
  next_n_neighbors: 90
  nwp_nodes: true
  patience: 15
  scheduler: cosine
  target_col: wind_speed
  weight_decay: 0.0001
  nwp_out_dim: 32
  nwp_heads: 4
