#!/usr/bin/env python3
"""Configs of the FL scenario study on the curtailed parks (FL_Contribution/reports/fl_scenarios_v1.md).

Base: configs/parks_v1/config_parks_v1_curt_v11_{fl_fedgradient,fl_fedavg,cl80}_static[_nolag].yaml
(x1 = parks_v1_curt_v11, capacity-weighted park statics). Written to configs/parks_v1/scenarios/,
results to results/fl_scenarios/. FL configs run with fine-tuning and evaluate the clients with
the global and the fine-tuned model (fl.fine_tune_eval_global); the local baseline is
train_local.py on the FedGradient config.

  A  scarce   training history 1/3/6/12 months before 2024-08-01, seeds 42/43/44; epochs/rounds,
              patience and fine-tune epochs scaled by 12/months (same number of optimizer steps)
  B  lopo     10 folds: park k of every client is a new park (never trained on), evaluated by
              its client's local model (fl.client_holdout), the global FL model and CL72
  C  mask     x1 and x4, no power lag; data.target_mask all | market_env (direct-marketer view:
              grid curtailment unknown) | none (x4 reference; x1 reference = *_static_nolag)

  python scripts/make_fl_scenarios.py            # writes the configs and scenarios/manifest.csv
"""

import copy
import os
import sys

import pandas as pd
import yaml

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BASE = os.path.join(REPO, 'configs', 'parks_v1')
OUT = os.path.join(BASE, 'scenarios')
RESULTS = 'results/fl_scenarios'
DATASETS = {'x1': 'parks_v1_curt_v11', 'x4': 'parks_v1_curt_v11_x4'}
MONTHS = {1: '2024-07-01', 3: '2024-05-01', 6: '2024-02-01', 12: '2023-07-24'}
SEEDS = (42, 43, 44)


class _Loader(yaml.SafeLoader):
    """Keeps !ENV tags verbatim (configs are copied, not resolved)."""


class _Env(str):
    pass


_Loader.add_constructor('!ENV', lambda loader, node: _Env(loader.construct_scalar(node)))
yaml.SafeDumper.add_representer(_Env, lambda d, v: d.represent_scalar('!ENV', str(v)))


def load(name: str) -> dict:
    with open(os.path.join(BASE, name)) as f:
        return yaml.load(f, Loader=_Loader)


def write(cfg: dict, name: str, header: str) -> str:
    os.makedirs(OUT, exist_ok=True)
    cfg['eval']['results_path'] = RESULTS
    path = os.path.join(OUT, f'config_{name}.yaml')
    with open(path, 'w') as f:
        f.write(f'# {header}\n# generated by scripts/make_fl_scenarios.py - do not edit\n')
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True, width=120)
    return os.path.relpath(path, REPO)[:-5]


def dataset(cfg: dict, ds: str) -> dict:
    cfg['data']['path'] = _Env(f"${{DATA_ROOT}}/synthetic/wind/{DATASETS[ds]}")
    return cfg


def fine_tune(cfg: dict, factor: int = 1) -> dict:
    cfg['fl'].update(fine_tune=True, fine_tune_eval_global=True, fine_tune_epochs=50 * factor)
    return cfg


def scale(cfg: dict, factor: int) -> dict:
    cfg['model']['epochs'] = 100 * factor
    cfg['model']['early_stopping']['patience'] = 10 * factor
    if cfg['model'].get('fl'):
        cfg['fl']['n_rounds'] = 100 * factor
        cfg['fl']['global_early_stopping']['patience'] = 10 * factor
    return cfg


def bases(suffix: str = 'static') -> dict:
    return {m: load(f'config_parks_v1_curt_v11_{m}_{suffix}.yaml') for m in ('fl_fedgradient', 'fl_fedavg', 'cl80')}


def scarce(rows: list) -> None:
    b = bases('static')
    for m, start in MONTHS.items():
        f = 12 // m
        for seed in SEEDS:
            for meth, cfg0 in b.items():
                cfg = scale(copy.deepcopy(cfg0), f)
                cfg['data']['train_start'] = start
                cfg['params']['random_seed'] = seed
                if meth.startswith('fl_'):
                    fine_tune(cfg, f)
                name = f'scen_scarce_m{m}_s{seed}_{meth}'
                rows.append({'scenario': 'scarce', 'months': m, 'seed': seed, 'method': meth,
                             'config': write(cfg, name, f'A scarce: {m} months training history, seed {seed}, {meth}')})


def lopo(rows: list) -> None:
    b = bases('static')
    clients = b['fl_fedgradient']['fl']['clients']
    holdout = list(b['fl_fedgradient']['data']['val_files'])
    for k in range(10):
        new = {c: [p[k]] for c, p in clients.items()}
        keep = {c: [x for i, x in enumerate(p) if i != k] for c, p in clients.items()}
        files = [x for c in keep for x in keep[c]]
        newparks = [new[c][0] for c in clients]
        for meth, cfg0 in b.items():
            cfg = copy.deepcopy(cfg0)
            cfg['data']['files'] = files
            if meth.startswith('fl_'):
                cfg['fl']['clients'] = keep
                cfg['fl']['client_holdout'] = new
                cfg['data']['val_files'] = newparks + holdout
                fine_tune(cfg)
            else:
                cfg['data']['holdout_files'] = newparks + holdout
            name = f'scen_lopo_k{k}_{meth.replace("cl80", "cl72")}'
            rows.append({'scenario': 'lopo', 'fold': k, 'seed': 42, 'method': meth,
                         'config': write(cfg, name, f'B lopo fold {k}: park {k} of every client is new, {meth}')})


def mask(rows: list) -> None:
    b = bases('static_nolag')
    for ds in ('x1', 'x4'):
        for spec in ('all', 'market_env', None):
            if ds == 'x1' and spec is None:
                continue            # reference: config_parks_v1_curt_v11_*_static_nolag (already run)
            for meth, cfg0 in b.items():
                cfg = dataset(copy.deepcopy(cfg0), ds)
                if spec:
                    cfg['data']['target_mask'] = spec
                if meth.startswith('fl_'):
                    fine_tune(cfg)
                name = f'scen_mask_{ds}_{spec or "none"}_{meth}'
                rows.append({'scenario': 'mask', 'dataset': ds, 'mask': spec or 'none', 'seed': 42, 'method': meth,
                             'config': write(cfg, name, f'C mask {spec or "none"} on {DATASETS[ds]} (no power lag), {meth}')})


def main():
    rows = []
    scarce(rows)
    lopo(rows)
    mask(rows)
    man = pd.DataFrame(rows)
    man.to_csv(os.path.join(OUT, 'manifest.csv'), index=False)
    print(man.groupby(['scenario', 'method']).size().to_string())
    print(f'{len(man)} configs -> {OUT}')


if __name__ == '__main__':
    sys.exit(main())
